/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FIBONACCI_H_RPCGEN
#define _FIBONACCI_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operands {
	int n;
};
typedef struct operands operands;

#define FIBONACCI_PROG 12345678
#define FIBONACCI_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define FIBONACCI 1
extern  int * fibonacci_1(operands *, CLIENT *);
extern  int * fibonacci_1_svc(operands *, struct svc_req *);
extern int fibonacci_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define FIBONACCI 1
extern  int * fibonacci_1();
extern  int * fibonacci_1_svc();
extern int fibonacci_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operands (XDR *, operands*);

#else /* K&R C */
extern bool_t xdr_operands ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FIBONACCI_H_RPCGEN */
